import { StyleSheet } from "react-native";
import { ds } from "../theme/designSystem";

export const connectedScreenStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: ds.colors.background },
  container: { padding: ds.spacing.lg, gap: ds.spacing.md, backgroundColor: ds.colors.background, paddingBottom: ds.spacing.xl },
  title: { fontSize: ds.typography.title, color: ds.colors.text, fontWeight: "700" },
  subtitle: { color: ds.colors.textMuted, marginBottom: ds.spacing.sm, fontSize: ds.typography.body },
  badge: {
    alignSelf: "flex-start",
    borderRadius: ds.radius.pill,
    paddingHorizontal: ds.spacing.md,
    paddingVertical: ds.spacing.xs,
    flexDirection: "row",
    alignItems: "center",
    gap: ds.spacing.sm,
    backgroundColor: ds.colors.successSoft,
  },
  badgeDot: { width: 8, height: 8, borderRadius: ds.radius.pill, backgroundColor: ds.colors.success },
  badgeText: { fontWeight: "600", fontSize: ds.typography.caption, color: ds.colors.success },
  card: { borderWidth: 1, borderColor: ds.colors.border, borderRadius: ds.radius.md, padding: ds.spacing.md, backgroundColor: ds.colors.surface },
  cardTitle: { fontWeight: "600", marginBottom: ds.spacing.sm, color: ds.colors.text, fontSize: ds.typography.heading },
  detailLabel: { color: ds.colors.textMuted, fontSize: ds.typography.caption, marginTop: ds.spacing.sm },
  detailValue: { color: ds.colors.text, fontSize: ds.typography.body },
  detailValueMono: { color: ds.colors.text, fontFamily: "monospace", fontSize: ds.typography.mono },
  input: {
    borderWidth: 1,
    borderColor: ds.colors.border,
    borderRadius: ds.radius.md,
    padding: ds.spacing.md,
    marginBottom: ds.spacing.sm,
    color: ds.colors.text,
    backgroundColor: ds.colors.surfaceSoft,
  },
  button: { backgroundColor: ds.colors.primary, borderRadius: ds.radius.md, paddingVertical: ds.spacing.md, alignItems: "center", minHeight: 44 },
  secondaryButton: { backgroundColor: ds.colors.surfaceSoft },
  newConversationButton: { minHeight: 36, paddingVertical: ds.spacing.sm, paddingHorizontal: ds.spacing.md, alignSelf: "flex-start" },
  buttonDisabled: { opacity: 0.6 },
  buttonText: { color: ds.colors.text, fontWeight: "600" },
  code: { fontFamily: "monospace", marginTop: ds.spacing.sm, color: ds.colors.textMuted, fontSize: ds.typography.mono },
  rowActions: { marginBottom: ds.spacing.sm },
  conversationList: { gap: ds.spacing.sm, marginBottom: ds.spacing.sm },
  conversationChip: {
    borderWidth: 1,
    borderColor: ds.colors.border,
    borderRadius: ds.radius.md,
    backgroundColor: ds.colors.surfaceSoft,
    paddingVertical: ds.spacing.sm,
    paddingHorizontal: ds.spacing.md,
    minWidth: 130,
  },
  conversationChipActive: {
    borderColor: ds.colors.primary,
    backgroundColor: ds.colors.primarySoft,
  },
  conversationChipTitle: { color: ds.colors.text, fontWeight: "600", fontSize: ds.typography.caption },
  conversationChipSub: { color: ds.colors.textMuted, fontSize: ds.typography.mono, marginTop: 2 },
  messagesWrap: { marginTop: ds.spacing.md, gap: ds.spacing.lg },
  messageBubble: {
    borderRadius: ds.radius.md,
    padding: ds.spacing.sm,
    borderWidth: 1,
    borderColor: ds.colors.border,
    maxWidth: "90%",
  },
  userBubble: { backgroundColor: ds.colors.primarySoft },
  assistantBubble: { backgroundColor: ds.colors.surfaceSoft },
  messageRole: { color: ds.colors.textMuted, fontSize: ds.typography.caption, marginBottom: ds.spacing.xs },
  messageText: { color: ds.colors.text, fontSize: ds.typography.body },
  chatTopBar: {
    paddingHorizontal: ds.spacing.lg,
    paddingTop: ds.spacing.sm,
    paddingBottom: ds.spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ds.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: ds.colors.border,
    backgroundColor: ds.colors.surface,
  },
  chatTopBackButton: {
    borderWidth: 1,
    borderColor: ds.colors.border,
    backgroundColor: ds.colors.surfaceSoft,
    borderRadius: ds.radius.md,
    paddingHorizontal: ds.spacing.md,
    paddingVertical: ds.spacing.sm,
  },
  chatTopBackButtonText: { color: ds.colors.text, fontSize: ds.typography.caption, fontWeight: "600" },
  chatTopTitleWrap: { alignItems: "center", flex: 1, paddingHorizontal: ds.spacing.sm },
  chatTopTitle: { color: ds.colors.text, fontSize: ds.typography.heading, fontWeight: "700" },
  chatTopSubtitle: { color: ds.colors.textMuted, fontSize: ds.typography.caption, marginTop: 2 },
  chatConnectedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: ds.spacing.xs,
    backgroundColor: ds.colors.successSoft,
    borderRadius: ds.radius.pill,
    paddingHorizontal: ds.spacing.sm,
    paddingVertical: ds.spacing.xs,
  },
  chatConnectedDot: { width: 8, height: 8, borderRadius: ds.radius.pill, backgroundColor: ds.colors.success },
  chatConnectedText: { color: ds.colors.success, fontSize: ds.typography.caption, fontWeight: "600" },
  chatModelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: ds.spacing.lg,
    paddingVertical: ds.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: ds.colors.border,
    backgroundColor: ds.colors.surface,
  },
  chatModelPill: {
    borderWidth: 1,
    borderColor: ds.colors.border,
    borderRadius: ds.radius.pill,
    backgroundColor: ds.colors.surfaceSoft,
    paddingHorizontal: ds.spacing.md,
    paddingVertical: ds.spacing.xs,
  },
  chatModelPillText: { color: ds.colors.text, fontSize: ds.typography.caption, fontWeight: "600" },
  chatModelMeta: { color: ds.colors.textMuted, fontSize: ds.typography.caption },
  chatQuickActionsScroll: { maxHeight: 54, flexGrow: 0, backgroundColor: ds.colors.surface },
  chatQuickActions: {
    paddingHorizontal: ds.spacing.lg,
    paddingVertical: ds.spacing.sm,
    gap: ds.spacing.sm,
    alignItems: "center",
    backgroundColor: ds.colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: ds.colors.border,
  },
  chatQuickActionPill: {
    borderWidth: 1,
    borderColor: ds.colors.border,
    borderRadius: ds.radius.pill,
    backgroundColor: ds.colors.surfaceSoft,
    paddingHorizontal: ds.spacing.md,
    paddingVertical: ds.spacing.xs,
    alignSelf: "center",
  },
  chatQuickActionText: { color: ds.colors.textMuted, fontSize: ds.typography.caption, fontWeight: "600" },
  chatMessagesScroll: { flex: 1 },
  chatMessagesContainer: { padding: ds.spacing.lg, paddingBottom: ds.spacing.xl },
  chatComposer: {
    borderTopWidth: 1,
    borderTopColor: ds.colors.border,
    backgroundColor: ds.colors.surface,
    paddingHorizontal: ds.spacing.md,
    paddingTop: ds.spacing.sm,
    paddingBottom: ds.spacing.md,
  },
  chatComposerRow: { flexDirection: "row", alignItems: "center", gap: ds.spacing.sm },
  chatCircleButton: {
    width: 38,
    height: 38,
    borderRadius: ds.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: ds.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: ds.colors.border,
  },
  chatCircleButtonText: { color: ds.colors.textMuted, fontSize: ds.typography.heading, lineHeight: ds.typography.heading + 1 },
  chatInput: {
    flex: 1,
    minHeight: 44,
    borderWidth: 1,
    borderColor: ds.colors.border,
    borderRadius: ds.radius.lg,
    backgroundColor: ds.colors.background,
    color: ds.colors.text,
    paddingHorizontal: ds.spacing.md,
    paddingVertical: ds.spacing.sm,
  },
  chatSendButton: {
    minHeight: 44,
    paddingHorizontal: ds.spacing.md,
    borderRadius: ds.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: ds.colors.primary,
  },
  chatSendButtonText: { color: ds.colors.text, fontSize: ds.typography.caption, fontWeight: "700" },
  chatMetaText: { color: ds.colors.textMuted, fontSize: ds.typography.mono, marginTop: ds.spacing.xs },
  chatMessageRow: { flexDirection: "row", alignItems: "flex-start", gap: ds.spacing.sm },
  chatMessageRowLeft: { justifyContent: "flex-start" },
  chatMessageRowRight: { justifyContent: "flex-start", flexDirection: "row-reverse" },
  chatAvatar: {
    width: 26,
    height: 26,
    borderRadius: ds.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    marginTop: ds.spacing.xs,
  },
  chatAvatarAssistant: { backgroundColor: ds.colors.surfaceSoft, borderWidth: 1, borderColor: ds.colors.border },
  chatAvatarUser: { backgroundColor: ds.colors.primary },
  chatAvatarText: { color: ds.colors.text, fontSize: 10, fontWeight: "700" },
  chatMessageTime: { color: ds.colors.textMuted, fontSize: 10, marginTop: ds.spacing.xs },
  chatTypingBubble: { minWidth: 110 },
  chatTypingText: { color: ds.colors.textMuted, fontSize: ds.typography.caption, fontStyle: "italic" },
  chatEmptyState: {
    borderWidth: 1,
    borderColor: ds.colors.border,
    borderRadius: ds.radius.md,
    padding: ds.spacing.lg,
    backgroundColor: ds.colors.surface,
    marginBottom: ds.spacing.md,
  },
  chatEmptyTitle: { color: ds.colors.text, fontWeight: "700", fontSize: ds.typography.heading },
  chatEmptySubtitle: { color: ds.colors.textMuted, marginTop: ds.spacing.xs, fontSize: ds.typography.caption },
  homeHeader: {
    paddingHorizontal: ds.spacing.lg,
    paddingTop: ds.spacing.lg,
    paddingBottom: ds.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: ds.colors.border,
    backgroundColor: ds.colors.surface,
  },
  homeHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  homeTitleWrap: { flex: 1 },
  homeTitle: { color: ds.colors.text, fontSize: 34, fontWeight: "700" },
  homeSubtitle: { color: ds.colors.textMuted, fontSize: ds.typography.caption, marginTop: 2 },
  homeOnlineDot: { width: 10, height: 10, borderRadius: ds.radius.pill, backgroundColor: ds.colors.success },
  homeWifi: { color: ds.colors.success, fontSize: 17, fontWeight: "700" },
  homeStatsBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: ds.spacing.lg,
    paddingVertical: ds.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: ds.colors.border,
    backgroundColor: ds.colors.surfaceSoft,
  },
  homeStatsLeft: { flexDirection: "row", alignItems: "center", gap: ds.spacing.md },
  homeStatsText: { color: ds.colors.textMuted, fontSize: ds.typography.caption },
  homeMain: { padding: ds.spacing.lg, gap: ds.spacing.md, paddingBottom: 80 },
  newConversationCard: {
    borderWidth: 1,
    borderColor: "#1e242c",
    borderRadius: ds.radius.lg,
    backgroundColor: "#020406",
    padding: ds.spacing.md,
  },
  newConversationHeaderRow: {
    position: "absolute",
    left: ds.spacing.md,
    top: ds.spacing.md,
  },
  newConversationIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "#00383b",
    alignItems: "center",
    justifyContent: "center",
  },
  newConversationIcon: { color: "#00d1d1", fontSize: 16, fontWeight: "700" },
  newConversationTitle: { color: ds.colors.text, fontSize: ds.typography.heading, fontWeight: "700" },
  newConversationSub: { color: ds.colors.textMuted, fontSize: ds.typography.caption, marginTop: 2, marginBottom: ds.spacing.sm, paddingLeft: 56 },
  newConversationInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: ds.spacing.sm,
    borderWidth: 1,
    borderColor: "#1d222a",
    borderRadius: ds.radius.md,
    backgroundColor: ds.colors.background,
    paddingHorizontal: ds.spacing.sm,
    minHeight: 54,
  },
  newConversationInput: { flex: 1, color: ds.colors.text, fontSize: ds.typography.body, paddingVertical: ds.spacing.sm },
  newConversationSendButton: {
    width: 36,
    height: 36,
    borderRadius: ds.radius.pill,
    backgroundColor: "#0f141a",
    borderWidth: 1,
    borderColor: ds.colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  newConversationSendIcon: { color: "#646b78", fontSize: 13 },
  suggestionWrap: { flexDirection: "row", flexWrap: "wrap", gap: ds.spacing.sm, marginTop: ds.spacing.sm },
  suggestionChip: {
    borderRadius: ds.radius.pill,
    backgroundColor: ds.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: ds.colors.border,
    paddingVertical: 8,
    paddingHorizontal: ds.spacing.md,
  },
  suggestionText: { color: ds.colors.textMuted, fontSize: ds.typography.caption },
  searchInput: {
    borderWidth: 1,
    borderColor: "#1e242c",
    borderRadius: ds.radius.md,
    backgroundColor: "#141a23",
    color: ds.colors.text,
    paddingHorizontal: ds.spacing.md,
    paddingVertical: 11,
  },
  sectionTitle: {
    color: ds.colors.textMuted,
    fontSize: ds.typography.caption,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: ds.spacing.sm,
    marginBottom: ds.spacing.xs,
  },
  convCard: {
    borderWidth: 1,
    borderColor: "#20242d",
    borderRadius: 14,
    backgroundColor: "#020406",
    padding: ds.spacing.md,
    marginBottom: ds.spacing.sm,
  },
  convCardPinned: {
    borderColor: "#00a3a3",
    backgroundColor: "#012325",
  },
  convCardInnerRow: { flexDirection: "row", alignItems: "flex-start", gap: ds.spacing.md },
  convIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#00383b",
  },
  convIcon: { fontSize: 16, color: "#e6f4f5" },
  convContent: { flex: 1 },
  convCardTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: ds.spacing.sm },
  convTitle: { color: ds.colors.text, fontSize: ds.typography.body, fontWeight: "700", flex: 1 },
  convPreview: { color: ds.colors.textMuted, fontSize: ds.typography.body, marginTop: ds.spacing.xs },
  convMeta: { color: ds.colors.textMuted, fontSize: ds.typography.mono, marginTop: ds.spacing.sm },
  convOpenCta: { color: ds.colors.primary, fontSize: ds.typography.caption, fontWeight: "700" },
  homeDangerButton: {
    marginTop: ds.spacing.md,
    borderWidth: 1,
    borderColor: ds.colors.danger,
    borderRadius: ds.radius.md,
    backgroundColor: ds.colors.dangerSoft,
    paddingVertical: ds.spacing.md,
    alignItems: "center",
  },
  homeDangerButtonText: { color: ds.colors.danger, fontWeight: "700" },
});

export const connectedScreenColors = {
  inputPlaceholder: ds.colors.textMuted,
} as const;
