import { StyleSheet } from "react-native";
import { ds } from "../../theme/designSystem";

export const chatDetailStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: ds.colors.background },
  chatTopBar: {
    paddingHorizontal: ds.spacing.lg,
    paddingTop: ds.spacing.sm,
    paddingBottom: ds.spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: ds.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: ds.colors.border,
    backgroundColor: ds.colors.surface,
  },
  chatTopTitleWrap: { alignItems: "flex-start", flex: 1, gap: ds.spacing.xs },
  chatTopTitle: { color: ds.colors.text, fontSize: ds.typography.heading, fontWeight: "700" },
  chatConnectedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: ds.spacing.xs,
    backgroundColor: ds.colors.successSoft,
    borderRadius: ds.radius.pill,
    paddingHorizontal: ds.spacing.sm,
    paddingVertical: ds.spacing.xs,
  },
  chatConnectedDot: { width: 8, height: 8, borderRadius: ds.radius.pill, backgroundColor: ds.colors.success },
  chatConnectedText: { color: ds.colors.success, fontSize: ds.typography.caption, fontWeight: "600" },
  chatTopMenuButton: {
    width: 38,
    height: 38,
    borderRadius: ds.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: ds.colors.border,
    backgroundColor: ds.colors.surfaceSoft,
  },
  chatTopMenuText: { color: ds.colors.text, fontSize: 18, lineHeight: 18 },
  chatModelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: ds.spacing.lg,
    paddingVertical: ds.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: ds.colors.border,
    backgroundColor: ds.colors.surface,
  },
  chatModelLeft: { flexDirection: "row", alignItems: "center", gap: ds.spacing.xs },
  chatModelIcon: { color: ds.colors.textMuted, fontSize: ds.typography.caption },
  chatModelPillText: { color: ds.colors.text, fontSize: ds.typography.caption, fontWeight: "600" },
  chatModelCaret: { color: ds.colors.textMuted, fontSize: ds.typography.caption },
  chatModelMeta: { color: ds.colors.textMuted, fontSize: ds.typography.caption },
  chatQuickActionsScroll: { maxHeight: 54, flexGrow: 0, backgroundColor: ds.colors.surface },
  chatQuickActions: {
    paddingHorizontal: ds.spacing.lg,
    paddingVertical: ds.spacing.sm,
    gap: ds.spacing.sm,
    alignItems: "center",
    backgroundColor: ds.colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: ds.colors.border,
  },
  chatQuickActionPillOutline: {
    borderWidth: 1,
    borderColor: ds.colors.border,
    borderRadius: ds.radius.pill,
    backgroundColor: ds.colors.surfaceSoft,
    paddingHorizontal: ds.spacing.md,
    paddingVertical: ds.spacing.xs,
    alignSelf: "center",
  },
  chatQuickActionText: { color: ds.colors.textMuted, fontSize: ds.typography.caption, fontWeight: "600" },
  chatMessagesScroll: { flex: 1 },
  chatMessagesContainer: { padding: ds.spacing.lg, paddingBottom: ds.spacing.xl },
  chatComposer: {
    borderTopWidth: 1,
    borderTopColor: ds.colors.border,
    backgroundColor: ds.colors.surface,
    paddingHorizontal: ds.spacing.md,
    paddingTop: ds.spacing.sm,
    paddingBottom: ds.spacing.md,
  },
  chatComposerRow: { flexDirection: "row", alignItems: "center", gap: ds.spacing.sm },
  chatCircleButton: {
    width: 38,
    height: 38,
    borderRadius: ds.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: ds.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: ds.colors.border,
  },
  chatCircleButtonText: { color: ds.colors.textMuted, fontSize: ds.typography.heading, lineHeight: ds.typography.heading + 1 },
  chatInput: {
    flex: 1,
    minHeight: 44,
    borderWidth: 1,
    borderColor: ds.colors.border,
    borderRadius: ds.radius.lg,
    backgroundColor: ds.colors.background,
    color: ds.colors.text,
    paddingHorizontal: ds.spacing.md,
    paddingVertical: ds.spacing.sm,
  },
  chatSendButton: {
    minHeight: 44,
    paddingHorizontal: ds.spacing.md,
    borderRadius: ds.radius.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: ds.colors.primary,
  },
  buttonDisabled: { opacity: 0.6 },
  chatSendButtonText: { color: ds.colors.text, fontSize: ds.typography.caption, fontWeight: "700" },
  chatMetaText: { color: ds.colors.textMuted, fontSize: ds.typography.mono, marginTop: ds.spacing.xs },
});

export const chatDetailColors = {
  inputPlaceholder: ds.colors.textMuted,
} as const;
